# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-30 09:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=31)),
            ],
            options={
                'verbose_name_plural': 'CATEGORY',
                'verbose_name': 'CATEGORY',
            },
        ),
        migrations.CreateModel(
            name='Editor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=31)),
                ('brief', models.CharField(blank=True, max_length=255)),
                ('fblink', models.CharField(blank=True, max_length=1023)),
                ('twlink', models.CharField(blank=True, max_length=1023)),
            ],
            options={
                'verbose_name_plural': 'EDITOR',
                'verbose_name': 'EDITOR',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=31)),
            ],
            options={
                'verbose_name_plural': 'MENU',
                'verbose_name': 'MENU',
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('menu', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ghoster.Menu')),
            ],
            options={
                'verbose_name_plural': 'PAGE',
                'verbose_name': 'PAGE',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publish', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(allow_unicode=True, max_length=255)),
                ('content', models.TextField()),
                ('thumbnail', models.URLField(blank=True)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('viewers', models.IntegerField(default=0)),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ghoster.Category')),
                ('editor', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ghoster.Editor')),
                ('page', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ghoster.Page')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name_plural': 'POST',
                'verbose_name': 'POST',
            },
        ),
    ]
