# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-07 15:29
from __future__ import unicode_literals

from django.db import migrations, models
import ghoster.models


class Migration(migrations.Migration):

    dependencies = [
        ('ghoster', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cover',
            field=models.ImageField(blank=True, upload_to=ghoster.models.content_file_name),
        ),
    ]
